# Generated by Django 2.2 on 2019-11-28 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_auto_20191127_2205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOutParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('guide', models.TextField(blank=True)),
                ('exercise_related', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=220)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('rounds', models.PositiveIntegerField(default=0)),
                ('guide', models.TextField(blank=True)),
                ('user_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
