# Generated by Django 2.2.7 on 2019-12-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutparts',
            name='workout_related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.WorkOut'),
            preserve_default=False,
        ),
    ]
